### ISSUE TITLE
Wybór skanera kodów

### ISSUE THREAD

**Issue by Szarp** [Litviniak/ZPI-BoKoLiMaNa#13]
### do ustalenia:
- kto się komunikuje z barcode (rpi, mikrokontroler)
- jaka obudowa (wystawiony za wewnątrz okrągły moduł, własne zabudowanie)
- który konkretnie moduł

**Comment by Szarp** [comment]
![obraz](https://user-images.githubusercontent.com/1409972/177528777-13bbfca7-0901-498f-880c-094f8f2ac206.png)

**Comment by Litviniak** [comment]
Ustalono, że wybieramy skaner GM60, będziemy robili mały w obudowie miejsce na wyjście do skanera. Co do komunikacji oba urządzenia(Arduino UNO, RPI) mają możliwość komunikacji, choć bardziej jestem za użyciem RPI jako modułu obsługującego czytnik, wycinając niepotrzebnego w tym przypadku pośrednika.
