### ISSUE TITLE
Webhook do servera z dc

### ISSUE THREAD

**Issue by Szarp** [Litviniak/ZPI-BoKoLiMaNa#2]
@Litviniak wydaje mi się że spoko pomysłem będzie skonfigurować hooka (notyfikacje z githuba do discorda) 

Na szybko coś takiego znalazłem: https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by Litviniak** [comment]
Webhook działa będzie jeszcze trzeba się przyjrzeć jak  filtrować dane bo domyślnie git nie wystawia za bardzo takiej możliwości.
